### ISSUE TITLE
Installing on 3.5

### ISSUE THREAD

**Issue by aringler-usgs** [usgs/libcomcat#150]
Hello Mike,

We were having difficulty installing this via 3.5 (@ewolin-usgs was giving us a demo).  However, we were able install this using conda on 3.7.  The conda package kept stalling when we it was trying to solve the environment.  The code we used is as follows:

```
conda create -n comcat --channel conda-forge python=3.5 ipython
conda activate comcat
conda config --add channels conda-forge
conda install libcomcat
```

What additional information could I provide you?

Thanks for your help.
Adam

**Comment by mhearne-usgs** [comment]
Adam - I was able to create 3.6 and 3.7 installations. I got a lot of conda package conflict errors trying to install with python 3.5 - probably the same thing you were seeing. I will update the documentation to not specify python 3.5.

As far as fixing the 3.5 installation problem, the conda universe is large and confusing, and figuring out how to unscramble the packages that are causing these problems is probably not worth the effort.
