### ISSUE TITLE
Installation without conda

### ISSUE THREAD

**Issue by samfux84** [usgs/libcomcat#189]
Hi,

I am managing the software stack on our universities HPC cluster. I got a request from a user to install libcomcat. We do not support conda on our cluster. When looking for installation instructions for libcomcat, I could only find conda instructions.

Is it possible to install libcomcat without conda ?

Thank you and best regards

Samuel

**Comment by emthompson-usgs** [comment]
Yes it is possible. You just have to manually install all of the dependencies and then libcomcat with pip.

**Comment by mhearne-usgs** [comment]
I'm trying to come up with conda instructions that work for the individual user, but I can't get conda to work currently on our test Linux system. I'll do some more research.

**Comment by emthompson-usgs** [comment]
Right, good point. I think the primary reason we started using conda to begin with is so that you don't need admin privileges to install the code and so you don't have to go do system admins to install the software.

**Comment by mhearne-usgs** [comment]
@samfux84 Is it possible for your user to install conda locally, in other words, just for their account?

If they (or you, as them) install miniconda under their home directory:
https://docs.conda.io/en/latest/miniconda.html

And then follow the installation instructions we provide, that should work, albeit only for that user. As @emthompson-usgs noted above, you can install manually, but it's a lot more work.

**Comment by samfux84** [comment]
@mhearne-usgs: Thank you for your reply. Users can install conda in their home directory, but for their home directory they have quota of 100'000 files/directories. Since conda installations create a huge number of files, this is most likely going to conflict with the file quota.

To avoid this, we try to provide software centrally installed. Therefore it would be nice to have a list of dependencies required to install libcomcat.

The install.sh file contains the following list:

      "python>=3.6"
      "impactutils"
      "ipython"
      "jupyter"
      "numpy"
      "obspy"
      "pandas"
      "pip"
      "pytest"
      "pytest-cov"
      "vcrpy"
      "xlrd"
      "xlwt"
      "openpyxl"
      "xlsxwriter"

Impactuils then requires  (according to its install.sh file)

    "beautifulsoup4"
    "cartopy"
    "libgdal=2.4.2"
    "fiona"
    "h5py"
    "ipython"
    "jupyter"
    "lxml"
    "matplotlib"
    "numpy"
    "openpyxl"
    "pandas"
    "paramiko"
    "pip"
    "pycrypto"
    "pytest"
    "pytest-cov"
    "pytest-mpl"
    "python>=3.6"
    "shapely"
    "xlrd"

Are there any other dependencies required ?

**Comment by mhearne-usgs** [comment]
@samfux84 I don't think there are any other dependencies *directly* required - assuming you're installing the other packages with pip, the dependencies of the above dependencies should be installed automatically with pip. If you're not using pip, then I think you have some more work to do.

Incidentally, you may want to tell your user that libcomcat is generally I/O-bound and not as limited by CPU speed, nor does it take advantage of parallel processing in any way.  If your users are doing large queries, mostly what they'll need is a system that won't be shut off while data is being retrieved.  Also, libcomcat is now supported on Windows, Mac and Linux.
