### ISSUE TITLE
getProducts flag 'version' not working

### ISSUE THREAD

**Issue by khaynie-usgs** [usgs/libcomcat#210]
**Describe the bug**
The flag version with the getProducts function is not working. I tested all options (all, preferred, first, last) and also tested with several event IDs. See examples in notebooks DetailEvent and Classes.

Error message: AttributeError: No VersionOption defined for first/last/all/preferred

**Environment (please complete the following information):**
- MacOS Mojave
- Python 3.7.3
- Libcomcat 1.3.5
- Numpy 1.17.3

**Comment by mhearne-usgs** [comment]
@khaynie-usgs  Are you testing the --version flag or the --get-version flag. Admittedly the help for the --version flag is not super clear - it is used by itself to tell you the version of the code you are using, like this:

`getproduct --version`
which should result in something like:
1.3.3

To get the first version of the ShakeMap intensity map for the recent Phillippines event:

`getproduct shakemap intensity.jpg -i us6000645n --get-version last -d ~/tmp/bual_data`

I get output that looks like this:

INFO 2019-10-30 19:02:19 | getproduct._get_product_from_detail: Downloaded us6000645n intensity.jpg to /Users/mhearne/tmp/bual_data/us6000645n/us6000645n_us_3_intensity.jpg

**Comment by khaynie-usgs** [comment]
Sorry for being unclear, @mhearne-usgs! When I run,

> eventid = 'nc73201181'
> detail = get_event_by_id(eventid, includesuperseded=True)
> data = detail.getProducts('phase-data', source='us', version='preferred')

I get the following error:

> AttributeError: No VersionOption defined for preferred

Options for version, in this case, can be set to 'all', 'first', 'last', or 'preferred', all of which give me the same attribute error.
