### ISSUE TITLE
Possibility to acess older versions of created shakemaps?

### ISSUE THREAD

**Issue by PeshawaLuqman** [usgs/libcomcat#211]
Hi, 

Am not sure if this fits as an issue here but I was wandering if there is the possibility to acess older versions of shakemaps that were created, I am trying trying to take a look at older version of shakemaps created fir the event id mentioned in the below code. 

Also, is it possible to get better quality shakemap outputs? 

ci3144585 = get_event_by_id('us2000bmcg');
product = ci3144585.getProducts('shakemap')[0]

img = product.getContentBytes('intensity.jpg')[0]
image = Image.open(io.BytesIO(img))

plt.figure(figsize=(10, 12))
plt.imshow(np.asarray(image))

Thank you for your help!

**Comment by emthompson-usgs** [comment]
There are two things you need to be aware of when looking for non 'preferred' product versions: 
1) There are multiple "sources" for each product. 
2) Versions are incremented by each contributor (usually referred to as the product "source")

By default the `getProducts` method only returns the most recent version from the preferred source. To get all versions from all sources you do this:
```
from libcomcat.search import get_event_by_id
event = get_event_by_id('us2000bmcg')
shakemaps = event.getProducts('shakemap', source='all', version='all')
```
Though, this is only returning 1 shakemap: 1 newest version for the only available source. 

I guess @mhearne-usgs will need to chime in and tell me what I'm doing wrong. Or is this a bug?

**Comment by jmfee-usgs** [comment]
@emthompson-usgs add the includedsuperseded parameter to get_event_by_id:
```
get_event_by_id(eventid, includesuperseded=True)
```

**Comment by mhearne-usgs** [comment]
@emthompson-usgs is correct, except that the get_event_by_id() call needs to include the includesuperseded=True parameter, documented here:

https://github.com/usgs/libcomcat/blob/master/docs/api.md#parameters

Modifying his example above will return 12 ShakeMaps, all from source 'us' (the USGS National Earthquake Information Center) . If you want non-JPG versions of the maps, you can download the intensity.ps.zip files (example: "https://earthquake.usgs.gov/archive/product/shakemap/us2000bmcg/us/1517881651419/download/intensity.ps.zip") . To get access to the ShakeMap grid data, you can look for either the grid.xml file or the ESRI raster files associated with the product.

If you have further questions, please feel free to email me directly at mhearne@usgs.gov

**Comment by PeshawaLuqman** [comment]
Thank you very much for your responses they were all very helpfull.
