### ISSUE TITLE
Code to download earthquake data for previous x years via query method

### ISSUE THREAD

**Issue by arjunbahl** [usgs/libcomcat#227]
start_year=datetime.datetime.strptime('1990','%Y')
all_yrs=[datetime.timedelta(x*365)+start_year for x in range(1,32)]

l=[]
for y in all_yrs:
	eq=pd.read_csv('https://earthquake.usgs.gov/fdsnws/event/1/query?format=xml&starttime={}-01-01&endtime={}-01-01&minmagnitude=4&format=csv'.format(y.year,y.year+1)) 
	l.append(eq)

d=pd.concat(l)
d=d.sort_values('time')
d=d.reset_index()
del d['index']

**Comment by mhearne-usgs** [comment]
Thank you for this comment. libcomcat was designed for users who need more detailed information than what is available via the ComCat API (all magnitudes, moment tensor information, etc.) This is a very clever use of the ComCat API - hopefully others will find it beneficial.
