### ISSUE TITLE
libcomcat.search fuction get_event_by_id() won't get scenario events

### ISSUE THREAD

**Issue by cbworden** [usgs/libcomcat#251]
**Describe the bug**
When requesting a scenario event (e.g., bssc2014903_m6p09_se) `get_event_by_id()` fails. I don't know if this is because the scenario exists at https://earthquake.usgs.gov/scenarios/eventpage/bssc2014903_m6p09_se/executive rather than at https://earthquake.usgs.gov/earthquakes/eventpage/bssc2014903_m6p09_se/executive or if there is some other issue, but it would be nice if scenario events would be found by `get_event_id()`.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environmnet (please complete the following information):**
 - OS: [e.g. macOS]
 - Python Version [e.g. 3.6]
- Libcomcat Version [e.g. 1.0]
- Numpy Version [e.g. 1.17]

**Additional context**

**Comment by cbworden** [comment]
Fixing this will likely fix ShakeMap issue 1133: https://github.com/usgs/shakemap/issues/1133

**Comment by jmfee-usgs** [comment]
@cbworden : it appears there is a `scenario` parameter for that purpose: https://github.com/usgs/libcomcat/blob/bfbc5bfd682cd78a6a08d1e0ba39264f3b122071/libcomcat/search.py#L219

**Comment by cbworden** [comment]
Okay. It looks like the products come under the label 'scenario-shakemap' rather than just 'shakemap' and a few other little quirks like that, but it basically seems to work.

**Comment by jmfee-usgs** [comment]
@cbworden : the separate product type and endpoint are by design to make it harder to accidentally process a scenario as an actual event.

**Comment by cbworden** [comment]
It makes sense, it just requires some poking around to figure out what changes. In this case I was dealing with three packages to get a program to handle both real events and scenarios, so it took a while to find all the places that needed "if" statements. Fun! :roll_eyes:
