### ISSUE TITLE
 pip install usgs-libcomcat does not work on Python 3.10.6

### ISSUE THREAD

**Issue by hhalaby** [usgs/libcomcat#265]
**Describe the bug**
`pip install usgs-libcomcat` does not work on python 3.10.6 because it's configured on PyPI as `Requires: Python <=3.10 `
**To Reproduce**
1. Create a venv with any python 3.10 minor version > 3.10.0
2. `pip install usgs-libcomcat` 

**Expected behavior**
Should install with all available 3.10 versions

**Screenshots**
![image](https://user-images.githubusercontent.com/86954225/206672458-bfdc38c8-077b-465a-a237-e9cf9a534c90.png)

![image](https://user-images.githubusercontent.com/86954225/206672551-673a1888-2bd5-4540-a5ad-7e2b12d68a61.png)

**Environmnet (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version 3.10.6
- Libcomcat Version 2.0.19

**Comment by hhalaby** [comment]
@emthompson-usgs @mhearne-usgs 
Hello again! Thank you for releasing libcomcat on PyPI. I've created the issue here as the GitLab instance requires me to sign in.
Is it possible to get a fix for this ?

**Comment by hhalaby** [comment]
solved with https://pypi.org/project/usgs-libcomcat/2.0.20/

**Comment by mhearne-usgs** [comment]
@hhalaby As noted above, there is now a release on PyPI that should support Python 3.10. Please let me know directly if this is not the case: mhearne@usgs.gov This version of the repository is being phased out in favor of a private GitLab instance where, unfortunately, we will not be able to accept issue submissions from members of the public.

https://code.usgs.gov/ghsc/esi/libcomcat-python
