### ISSUE TITLE
Can I use this to download all the landslide ground failure images?

### ISSUE THREAD

**Issue by thomasastanley** [usgs/libcomcat#266]
**Is your feature request related to a problem? Please describe.**
I am trying to download all the landslide ground failure maps, but I don't want to click endlessly through the website. Will this software let me do it?

eg https://earthquake.usgs.gov/realtime/product/ground-failure/6000jllz_cloud/us/1676665996918/jessee_2018_model.tif

**Describe the solution you'd like**
I'd like a path to a download directory where all the files are. 

**Describe alternatives you've considered**
Maybe the download paths can be generated in an automated way, but I don't know how to predict these:
6000jllz_cloud  1676665996918

**Additional context**
In the future, I will want to check for new or updated files on a daily basis.

**Comment by emthompson-usgs** [comment]
Yes, that is what this software is meant for. Note that the repository has recently moved here: 
https://code.usgs.gov/ghsc/esi/libcomcat-python
I'll ask @mhearne-usgs to archive the old repo and have it point to the new one. 

The command you probably want is `getproduct`, documented here:
https://code.usgs.gov/ghsc/esi/libcomcat-python/-/blob/main/docs/cli.md#getproduct
Note that the documentation has some examples and hopefully that is enough. If you have trouble, let us know.

**Comment by thomasastanley** [comment]
thanks, i will check it out
