### ISSUE TITLE
possible bug in getphases with catalog option

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/libcomcat#92]
When running the getphases command to extract phase data from a specific catalog, the program uses the preferred contributor's eventid when naming the output file (the phase data is from the correct catalog).

For example, the following command creates a file named `uwphases/us2000ahu1_phases.csv` (using the preferred event id) instead of the expected `uwphases/uw61304842_phases.csv` (using the UW catalog event id:
```
getphases --catalog uw -m 2.5 10 --start-time 2017-09-08 --end-time 2017-09-09 uwphases
```

**Comment by mhearne-usgs** [comment]
Closed in PR #109
